### ISSUE TITLE
minitest-reporters

### ISSUE THREAD

**Issue by svoop** [garrettdimon/minitest-heat#10]
Very nice gem, thanks a lot!

How can it be used [minitest-reporters](https://github.com/minitest-reporters/minitest-reporters)? Looking at the source I'm not sure it's currently compatible at this point.

If implemented similarly to other reporters such as [minitest-sound](https://github.com/y-yagi/minitest-sound), a setup might look something like:

```ruby
require 'minitest/reporters'
require 'minitest/sound/reporter'
require 'minitest/heat/reporter'
Minitest::Reporters.use! [Minitest::Sound::Reporter.new, Minitest::Heat::Reporter.new]
```

**Comment by garrettdimon** [comment]
I'd have to look into that, but I don't see it being something I'd actively work on since I don't use minitest-reporters myself. If there's a relatively simple way to enable compatibility without complicating things too much, I'd certainly be happy to merge a PR for it.

I built it without considering how (or if) it would work with minitest-reporters. I had explored the idea of using minitest-reporters previously with a rough idea, but with the [extensions API for Minitest](https://github.com/seattlerb/minitest#writing-extensions-), it felt lower-friction to use that directly instead.
